steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - europe-north2-docker.pkg.dev/my-collaborative-todo/cloud-run-source-deploy/todos-backend:latest
      - .
      - '-f'
      - Dockerfile
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-north2-docker.pkg.dev/my-collaborative-todo/cloud-run-source-deploy/todos-backend:latest
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - todos-backend
      - '--platform=managed'
      - --image=europe-north2-docker.pkg.dev/my-collaborative-todo/cloud-run-source-deploy/todos-backend:latest
      - --region=europe-north2
      - '--quiet'
    id: Deploy
    entrypoint: gcloud

images:
  - europe-north2-docker.pkg.dev/my-collaborative-todo/cloud-run-source-deploy/todos-backend:latest

options:
  logging: CLOUD_LOGGING_ONLY

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - todos-backend
